# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pauli_matrices": "core.pauli.ipynb",
         "pauli_names": "core.pauli.ipynb",
         "PauliOperator": "core.pauli.ipynb",
         "computational_to_pauli_state": "tomography.ipynb",
         "pauli_to_computational_state": "tomography.ipynb",
         "pauli_transfer_matrix_unitary": "tomography.ipynb",
         "QuantumGate": "tomography.ipynb"}

modules = ["core/pauli.py",
           "tomography.py"]

doc_url = "https://caldwellshane.github.io/notes/"

git_url = "https://github.com/caldwellshane/notes/tree/main/"

def custom_doc_links(name): return None
